server:
  port: 1000 #配置端口名
  servlet:
    context-path: /learner.me #访问路径为http://localhost:1000/learner.me/
spring:
  #配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learner?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      read-only: false
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      maximum-pool-size: 60
      minimum-idle: 10
    ## Mybatis 配置
  resources:
    #静态资源
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mvc:
    # 所有静态资源
    static-path-pattern: /**

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    check-template-location: true
  http:
    encoding:
      enabled: true
      charset: UTF-8
  #设置重启的目录
  #spring.devtools.restart.additional-paths: src/main/java
  #classpath目录下的WEB-INF文件夹内容修改不重启

  #jedis:
    ## Redis服务器地址
    #host: 127.0.0.1
    ## Redis服务器连接端口
    #port: 6379
    ## Redis服务器连接密码（默认为空）
    #password:
    ## Redis数据库索引（默认为0）
    #database: 0
    #pool:
      ## 连接池最大连接数（使用负值表示没有限制）
      #max-active: 8
      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      #max-wait: 1
      ## 连接池中的最大空闲连接
      #max-idle: 500
      ## 连接池中的最小空闲连接
      #min-idle: 0
    ## 连接超时时间（毫秒）
    #timeout: 0
mybatis:
  type-aliases-package: com.example.learner.bean
  mapper-locations: classpath:mapper/*.xml
